version: "3.8"

services:
  qread:
    image: ghcr.io/tzc110112/qread:latest
    container_name: qread
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Shanghai

      # =========== admin ===========
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: adminadmin
      ADMIN_UPDATE: "false"

      # =========== 用户权限 ===========
      USER_SOURCE: "0"
      USER_ALLOWCHANGE: "true"
      USER_PROXYPNG: "false"

      # =========== 自动采集 ===========
      AUTO_CRAWL: "true"
      AUTO_UPDATE: "true"

    volumes:
      - ./appdata:/app/storage
